profiler/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'employee'
urlpatterns = [
    path('', views.index, name='index'), 
    path('login', views.loginview, name='loginview'),
    path('login/process', views.process, name='process'),
    path('logout', views.processlogout, name='processlogout'),
    path('add', views.add, name='add'),
    path('searcjh', views.search, name='search'),
    path('processadd', views.processadd, name='processadd'),
    path('<int:profile_id>/detail/', views.detail, name='detail'),
    path('<int:profile_id>/delete/', views.delete, name='delete'),
    path('<int:profile_id>/edit/', views.edit, name='edit'),
    path('<int:profile_id>/processedit/', views.processedit, name='processedit'),
    path('addcomment',views.addcomment, name='addcomment'),
    path('<int:profile_id>/update_attendance/', views.update_attendance, name='update_attendance'),
    path('on_leave/', views.on_leave, name='on_leave'),
    path('attendances/', views.attendances, name='attendances'),
    path('signup/', views.signup, name='signup'),
    

    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from datetime import datetime
import os
import random
from django.utils import timezone
from django.utils.html import mark_safe


now = timezone.now()

def image_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    _now = datetime.now()

    return 'profile_pic/{year}-{month}-{imageid}-{basename}-{randomstring}{ext}'.format(imageid = instance, basename=basefilename, 
    randomstring = randomstr, ext=file_extension, year=_now.strftime('%Y'), month=_now.strftime('%m'), day=_now.strftime('%d'))



class Employee(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('on_leave', 'On Leave'),
    ]

    emp_fname = models.CharField(max_length=200, verbose_name='First Name',)
    emp_lname = models.CharField(max_length=200, verbose_name='Last Name')
    emp_email = models.EmailField(unique=True, max_length=200, verbose_name='Email')
    emp_position = models.CharField(max_length=200, verbose_name='Position')
    salary = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    emp_image = models.ImageField(upload_to=image_path, default='profile_pic/image.jpg')
    pub_date = models.DateField(default=now)
    contact_number = models.CharField(max_length=15, verbose_name='Contact Number', blank=True, null=True)
    birthday = models.DateField(null=True, blank=True, verbose_name='Birthday')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name='Status')  # New field

    def __str__(self):
        return self.emp_fname + ' ' + self.emp_lname

    def image_tag(self):
        return mark_safe('<img src="/users/media/%s" width="50" height="50" />' % self.emp_image)

    def __str__(self):
        return self.emp_email
    
    def get_status_display(self):
        return self.status.capitalize()

class EmployeeAddress(models.Model):
    employee = models.OneToOneField('Employee', on_delete=models.CASCADE, related_name='address')
    street_address = models.CharField(max_length=255, verbose_name='Street Address', default='')
    city = models.CharField(max_length=100, verbose_name='City', default='')
    state = models.CharField(max_length=100, verbose_name='State', default='')
    zip_code = models.CharField(max_length=20, verbose_name='ZIP Code', default='')

    def __str__(self):
        return f'{self.employee.emp_fname} {self.employee.emp_lname} Address'
    
class Attendance(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField()
    attended = models.BooleanField(default=False)

    
class Comment(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField(default='null')
    body = models.TextField(default='null')
    created_on = models.DateTimeField(default=now)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('email', )

users/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Employee, Comment, EmployeeAddress, Attendance
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, permission_required
from datetime import datetime, timedelta 
import calendar
from .forms import CustomUserCreationForm

def index(request): 
    employee_list = Employee.objects.all().order_by('-id')
    paginator = Paginator(employee_list, 6)

    page_number = request.GET.get('page')

    employee_list = paginator.get_page(page_number)
    return render(request, 'users/index.html', {'page_obj': employee_list})
   

@login_required(login_url='/users/login')
@permission_required('users.add_employee', login_url='/users/login')
def add(request):
    return render(request, 'users/add.html')

def search(request):
    term = request.GET.get('search', '')
    employee_list = Employee.objects.filter( Q(emp_fname__icontains=term) | Q(emp_lname__icontains=term)).order_by('-id')

    paginator = Paginator(employee_list, 6)

    page_number = request.GET.get('page')

    employee_list = paginator.get_page(page_number)
    return render(request, 'users/index.html', {'page_obj': employee_list})


def calculate_salary(hours_worked, hourly_rate):
    # Define your salary calculation logic here based on hours_worked and hourly_rate
    return hours_worked * hourly_rate

from django.http import HttpResponseForbidden


def processadd(request):
    fname = request.POST.get('fname')
    lname = request.POST.get('lname')
    email = request.POST.get('email')
    hours_worked = float(request.POST.get('hours_worked'))
    hourly_rate = float(request.POST.get('hourly_rate'))
    position = request.POST.get('position')
    contact_number = request.POST.get('contact_number')

    birthday_str = request.POST.get('birthday')
    birthday = datetime.strptime(birthday_str, '%Y-%m-%d').date() if birthday_str else None

    if request.FILES.get('image'):
        employee_pic = request.FILES.get('image')
    else:
        employee_pic = 'profile_pic/image.jpg'

    try:
        n = Employee.objects.get(emp_email=email)
        return render(request, 'users/add.html', {'error_message': "Duplicated email: " + email})

    except ObjectDoesNotExist:
        calculated_salary = calculate_salary(hours_worked, hourly_rate)

        employee = Employee.objects.create(
            emp_email=email, emp_fname=fname, emp_lname=lname,
            emp_position=position, emp_image=employee_pic,
            salary=calculated_salary, contact_number=contact_number,
            birthday=birthday  # Include the birthday field
        )
        employee.save()

        address = EmployeeAddress.objects.create(
            employee=employee,
            street_address=request.POST.get('street_address'),
            city=request.POST.get('city'),
            state=request.POST.get('state'),
            zip_code=request.POST.get('zip_code'),
        )
        address.save()

        return HttpResponseRedirect('/users')


@login_required(login_url='/users/login')
@permission_required('users.change_employee', login_url='/users/login')
def detail(request, profile_id):
    try:
        employee = Employee.objects.get(pk=profile_id)
        comments = Comment.objects.filter(employee_id=profile_id)
        comments_count = Comment.objects.filter(employee_id=profile_id).count()

        # Get the start date (Monday) of the current week
        today = datetime.today()
        start_of_week = today - timedelta(days=today.weekday())

        # Generate dates for the current week (Monday to Sunday)
        week_dates = [(start_of_week + timedelta(days=i)).strftime('%b. %d, %Y') for i in range(7)]

        # Fetch attendance data for the employee
        attendance_days = Attendance.objects.filter(employee=employee)

    except Employee.DoesNotExist:
        raise Http404("Profile does not exist")

    return render(request, 'users/detail.html', {'employee': employee, 'comments': comments, 'comments_count': comments_count, 'attendance_days': attendance_days, 'week_dates': week_dates})

def delete(request, profile_id):
    Employee.objects.filter(id=profile_id).delete()
    return HttpResponseRedirect('/users')
@login_required(login_url='/users/login')
@permission_required('users.change_employee', login_url='/users/login')
def edit(request, profile_id):
    try:
        employee = Employee.objects.get(pk=profile_id)  
    except Employee.DoesNotExist:
        raise Http404("profile does not exist")
    return render(request, 'users/edit.html', {'employee' : employee})

def processedit(request, profile_id):
    employee = get_object_or_404(Employee, pk=profile_id)
    profile_pic = request.FILES.get('image')

    try:
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        position = request.POST.get('position')
        hours_worked = float(request.POST.get('hours_worked'))
        hourly_rate = float(request.POST.get('hourly_rate'))
        contact_number = request.POST.get('contact_number')
        street_address = request.POST.get('street_address')
        city = request.POST.get('city')
        state = request.POST.get('state')
        zip_code = request.POST.get('zip_code')
        birthday = request.POST.get('birthday')
        status = request.POST.get('status', 'active')  # Add this line to get the status field

    except (KeyError, Employee.DoesNotExist):
        return render(request, 'users/detail.html', {'employee': employee, 'error_message': "Problem Updating Records"})
    else:
        # Convert the birthday string to a datetime object
        if birthday:
            birthday = datetime.strptime(birthday, '%Y-%m-%d').date()

        # Calculate the salary based on the formula
        calculated_salary = calculate_salary(hours_worked, hourly_rate)

        # Update the Employee object with the calculated salary, birthday, and status
        employee.emp_fname = fname
        employee.emp_lname = lname
        employee.emp_email = email
        employee.emp_position = position
        employee.salary = calculated_salary
        employee.contact_number = contact_number
        employee.birthday = birthday
        employee.status = status  # Set the status

        if profile_pic:
            employee.emp_image = profile_pic

        employee.save()

        # Update the EmployeeAddress object
        address, created = EmployeeAddress.objects.get_or_create(employee=employee)
        address.street_address = street_address
        address.city = city
        address.state = state
        address.zip_code = zip_code
        address.save()

        return HttpResponseRedirect(reverse('employee:detail', args=(profile_id,)))


    
def loginview(request):
    return render(request, 'users/login.html')

def process(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    
    user = authenticate(username = username, password = password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect('/users')
    else:
        return render (request, 'users/login.html', {'error_message': "Login Failed"})
    
def processlogout(request):
    logout(request)
    return HttpResponseRedirect('/users/login')

def addcomment(request):
    comment_text = request.POST.get('comment')
    employee_id = request.POST.get('employee_id')
    name = request.POST.get('name')
    email = request.POST.get('email')

    comment = Comment.objects.create(employee_id=employee_id, body=comment_text, name=name, email=email)
    comment.save()
    return HttpResponseRedirect(reverse('employee:detail', args=(employee_id, )))


def update_attendance(request, profile_id):
    employee = get_object_or_404(Employee, pk=profile_id)

    if request.method == 'POST':
        attendance_dates = request.POST.getlist('attendance_dates')

        # Update or create attendance records
        for date_str in attendance_dates:
            date = datetime.strptime(date_str, '%b. %d, %Y').date()
            attendance, created = Attendance.objects.get_or_create(employee=employee, date=date)
            attendance.attended = True  # You might have another way to determine attendance
            attendance.save()

    return HttpResponseRedirect(reverse('employee:detail', args=(profile_id,)))

def get_status_display(self):
    return dict(Employee.STATUS_CHOICES)[self.status]
def on_leave(request):
    # Retrieve the list of employees on leave
    employees_on_leave = Employee.objects.filter(status='on_leave')

    # Paginate the employees, with 6 employees per page
    paginator = Paginator(employees_on_leave, 6)
    page_number = request.GET.get('page')

    try:
        employees_on_leave = paginator.page(page_number)
    except PageNotAnInteger:
        employees_on_leave = paginator.page(1)
    except EmptyPage:
        employees_on_leave = paginator.page(paginator.num_pages)

    context = {
        'employees_on_leave': employees_on_leave
    }

    return render(request, 'users/on_leave.html', context)

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

@login_required(login_url='/users/login')
@permission_required('users.add_employee', login_url='/users/login')
def attendances(request):
    all_employees = Employee.objects.all()
    selected_employee_id = request.GET.get('employee_id')

    if selected_employee_id:
        selected_employee = get_object_or_404(Employee, id=selected_employee_id)

templates/users/add.html
{% extends 'base.html' %}

{% block title %}
    Add New User
{% endblock %}

{% block content %}
    {% if error_message %}
    <p class="alert alert-danger">
        <strong>{{ error_message }}</strong>
    </p>
    {% endif %}
    <h1 class="text-center mb-4" style="color: #88a376">ADD EMPLOYEE</h1>
    <form action="{% url 'employee:processadd' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-md-6">
                <label style="color: black;">First Name</label>
                <input type="text" name="fname" id="fname" class="form-control" required>
            </div>
            <div class="form-group col-md-6">
                <label style="color: black;">Last Name</label>
                <input type="text" name="lname" id="lname" class="form-control" required>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label style="color: black;">Email</label>
                <input type="email" name="email" id="email" class="form-control" required>
            </div>
            <div class="form-group col-md-6">
                <label style="color: black;">Position</label>
                <input type="text" name="position" id="position" class="form-control">
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label style="color: black;">Birthdate</label>
                <input type="date" name="birthday" id="birthday" class="form-control" placeholder="YYYY-MM-DD" value="{{ employee.birthday }}">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label style="color: black;">Hours Worked</label>
                <input type="number" name="hours_worked" id="hours_worked" class="form-control" required>
            </div>
            <div class="form-group col-md-6">
                <label style="color: black;">Hourly Rate (₱)</label>
                <input type="number" name="hourly_rate" id="hourly_rate" class="form-control" required step="50">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label style="color: black;">Contact No. (+63)</label>
                <input type="text" name="contact_number" id="contact_number" class="form-control" maxlength="10">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label style="color: black;">Street Address</label>
                <input type="text" name="street_address" id="street_address" class="form-control">
            </div>
            <div class="form-group col-md-6">
                <label style="color: black;">City</label>
                <input type="text" name="city" id="city" class="form-control">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label style="color: black;">State</label>
                <input type="text" name="state" id="state" class="form-control" value="{{ employee.address.state }}" placeholder="(Optional)">
            </div>
            <div class="form-group col-md-6">
                <label style="color: black;">ZIP Code</label>
                <input type="text" name="zip_code" id="zip_code" class="form-control">
            </div>
        </div>
    

        <div class="form-group">
            <label style="color: black;">User Image</label><br>
            <input type="file" name="image" id="image">
        </div>

        <button type="submit" class="btn mt-2" style="background-color:#88a78e; color: white;">Add</button>
    </form>

{% endblock %}

templates/users/attendance.html
{% extends 'base.html' %}

{% block title %}Attendance{% endblock %}

{% block content %}
<h1 class="text-center mb-4" style="color: #88a376">ATTENDANCES</h1>
<div class="container">

    <!-- Form to select an employee -->
    <form method="get" action="{% url 'employee:attendances' %}" class="mb-4">
        <div class="form-row align-items-end">
            <div class="col-md-4">
                <label for="employee_select" style="color: black; font-size: larger;"><strong>Select Employee:</strong></label>
                <select name="employee_id" id="employee_select" class="form-control">
                    <option value="" {% if not selected_employee %}selected{% endif %}>All Employees</option>
                    {% for emp in all_employees %}
                        <option value="{{ emp.id }}" {% if selected_employee and emp.id == selected_employee.id %}selected{% endif %}>{{ emp.emp_fname }} {{ emp.emp_lname }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-2">
                <button type="submit" class="btn" style="background-color: #88a376; color: white;">Filter</button>
            </div>
        </div>
    </form>

    <!-- Display attendance data -->
    <table class="table table-bordered">
        <thead style="background-color:#7a876f;">
        <tr>
            <th>Employee Name</th>
            <th>Date</th>
            <th>Attended</th>
        </tr>
        </thead>
        <tbody>
        {% for attendance in filtered_attendance_days %}
        <tr>
            <td>{{ attendance.employee.emp_fname }} {{ attendance.employee.emp_lname }}</td>
            <td>{{ attendance.date|date:"M. d, Y" }}</td>
            <td>{% if attendance.attended %}Yes{% else %}No{% endif %}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if filtered_attendance_days.paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if filtered_attendance_days.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ filtered_attendance_days.previous_page_number }}">previous</a>
                {% endif %}

                {% if filtered_attendance_days.has_next %}
                    <a href="?page={{ filtered_attendance_days.next_page_number }}">next</a>
                    <a href="?page={{ filtered_attendance_days.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

    <!-- Display message if no attendance data is available -->
    {% if filtered_attendance_days|length == 0 %}
        <p>No attendance data available.</p>
    {% endif %}
</div>
{% endblock %}

templates/users/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ employee.emp_fname }} {{ employee.emp_lname }}
{% endblock %}

{% block content %}
    {% if error_message %}
        <p class="alert alert-danger">
            <strong>{{ error_message }}</strong>
        </p>
    {% endif %}

    <div class="row">
        <div class="col-lg-6">
            <div class="img-responsive">
                <img src="/users/media/{{ employee.emp_image }}" alt="" class="img-rounded" width="300">
            </div><br>
            <div class="mb-5" style="color: black;">
                <h1>{{ employee.emp_fname }} {{ employee.emp_lname }}</h1>
                <p><strong>{{ employee.emp_email }}</strong></p>
                {% if employee.status == 'active' %}
                    <p style="color: green; font-weight: bolder;" ><strong style="color: black; font-weight: lighter;">Status:</strong> Active</p>
                {% elif employee.status == 'on_leave' %}
                    <p style="color: red; font-weight: bolder;"><strong style="color: black;font-weight: bold;">Status:</strong> On Leave</p>
                {% endif %}
                <p><strong>Position:</strong> {{ employee.emp_position }}</p>
                <p><strong>Salary:</strong> ₱{{ employee.salary }}/Day</p>
                <p><strong>Contact No.:</strong> (+63)&nbsp;{{ employee.contact_number }}</p>
                <p><strong>Birthday:</strong> {{ employee.birthday }}</p>
                <p><strong>Address:</strong></p>
                <p>{{ employee.address.street_address }}, {{ employee.address.city }}, {{ employee.address.state }} {{ employee.address.zip_code }}</p>
            </div>
            <div class="btn-group mt-5 mx-5">
                {% if user.is_staff %}
                    <a href="{% url 'employee:delete' employee.id %}" class="btn btn-l btn-danger">Delete</a>
                    <a href="{% url 'employee:edit' employee.id %}" class="btn btn-l btn-info">Edit</a>
                {% endif %}
                <a href="{% url 'employee:index' %}" class="btn btn-l btn-success">Return</a>
            </div>
        </div>

        <div class="col-lg-6" style="color: black;">
            <h2>COMMENTS</h2>
            <p><strong>Total of</strong> {{ comments_count }}</p>
            {% if comments_count > 0 %}
                {% for comment in comments %}
                    {% if comment.active %}
                        <p><strong>{{ comment.name }}</strong>: {{ comment.body }}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <hr>
            <br>
            
            <form action="{% url 'employee:addcomment' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label><strong>Comments:</strong></label>
                    <textarea name="comment" id="comment" cols="30" rows="5" class="form-control" required></textarea>
                </div>
                <input type="hidden" name="employee_id" id="employee_id" value="{{ employee.id }}">
                <input type="hidden" name="name" id="name" value="{{ user.username }}">
                <input type="hidden" name="email" id="email" value="{{ user.email }}">

                <button type="submit" class="btn btn-sm " style="background-color:#88a78e; color: white;">Add Comment</button>
            </form>

            <h2>Attendance Checklist</h2>
            <form method="post" action="{% url 'employee:update_attendance' employee.id %}">
                {% csrf_token %}
                <table class="table table-bordered">
                    <thead style="background-color: #7a876f;">
                        <tr>
                            <th>&nbsp;</th>
                            {% for date in week_dates %}
                                <th>{{ date }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Attendance</td>
                            {% for date in week_dates %}
                                <td>
                                    <input type="checkbox" name="attendance_dates" value="{{ date }}" {% if date in attendance_dates %}checked{% endif %}>
                                </td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
                <button type="submit" class="btn btn-sm" style="background-color:#88a78e; color: white; ">Update Attendance</button>
            </form>

            <script>
                //display birthday 
                function showBirthdayAlert() {
                    alert("It's {{ employee.emp_fname }}'s birthday! 🎉 Greet them a Happy Birthday!");

                }
                // Check if today is the birthday
                var today = new Date();
                var birthday = new Date("{{ employee.birthday|date:'Y-m-d' }}");
                birthday.setFullYear(today.getFullYear());  // Set the year of the birthday to current year
                if (today.toDateString() === birthday.toDateString()) {
                    //show the alert
                    window.onload = showBirthdayAlert;
                }
            </script>
        </div>
    </div>
{% endblock %}

templates/users/index.html
{% extends 'base.html' %}

{% block title %}
    Employee List
{% endblock %}
{% block content %}
    <h1 class="text-center mb-4" style="color: #88a376">EcoCraft</h1>

    <form action="{% url 'employee:search' %}" method="GET" class="mb-4">
        <div class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search" required>
            <div class="input-group-append">
                <button class="btn btn-search" style="background-color:#88a78e;">Search</button>
            </div>
        </div>
    </form>

    {% if page_obj %}
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <thead style="background-color: #7a876f;">
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Position</th>
                    <th>Profile Image</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in page_obj %}
                <tr>
                    <td>{{ employee.emp_fname }}</td>
                    <td>{{ employee.emp_lname }}</td>
                    <td>{{ employee.emp_email }}</td>
                    <td>{{ employee.emp_position}}</td>
                    <td>
                        <a href="{% url 'employee:detail' employee.id %}">
                            <img src="media/{{employee.emp_image}}" alt="empimage" width="50" class="rounded-circle">
                        </a>
                    </td>
                </tr>
                {% endfor %}    
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}



                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
    {% else %}
        <p>No Records Found</p> 
    {% endif %}
    
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
 
        <div class="col-md-6">
            <h2 style="color: black;">Welcome to Eco Craft Employee Management</h2>
            <p style="color: black;">
                Our Employee Management System provides amazing features for managing our employees. If you don't have an staff account yet,
                <a href="{% url 'employee:signup' %}" style="color: #88a376;">Sign up here</a>.
            </p>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    {% if error_message %}
                        <p class="alert alert-danger">
                            <strong>{{ error_message }}</strong>
                        </p>
                    {% endif %}

                    <div class="text-center">
                        <h2 style="color: black;">Login Form</h2>
                    </div>

                    <form action="{% url 'employee:process' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label style="color: black;">Username</label>
                            <input type="text" name="username" id="username" class="form-control" placeholder="Enter Username" autocomplete="off" required>
                            <label style="color: black;">Password</label>
                            <input type="password" name="password" id="password" class="form-control" placeholder="Enter Password" required>
                        </div>
                        <button type="submit" class="btn mt-2" style="background-color:#88a78e; color: white;">Login</button>
                    </form>

                    <p class="mt-3" style="color: black;">
                        Don't have an account? <a href="{% url 'employee:signup' %}" style="color: #88a376;">Sign up here</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}